//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhinoStableDiffuison {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Usersetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static Usersetting defaultInstance = ((Usersetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Usersetting())));
        
        public static Usersetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsCNOn {
            get {
                return ((bool)(this["IsCNOn"]));
            }
            set {
                this["IsCNOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\")]
        public string imagepath {
            get {
                return ((string)(this["imagepath"]));
            }
            set {
                this["imagepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ControlNetModel {
            get {
                return ((string)(this["ControlNetModel"]));
            }
            set {
                this["ControlNetModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ControlNetModel1 {
            get {
                return ((string)(this["ControlNetModel1"]));
            }
            set {
                this["ControlNetModel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ControlNetModel2 {
            get {
                return ((string)(this["ControlNetModel2"]));
            }
            set {
                this["ControlNetModel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ControlNetModel3 {
            get {
                return ((string)(this["ControlNetModel3"]));
            }
            set {
                this["ControlNetModel3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAutoSave {
            get {
                return ((bool)(this["IsAutoSave"]));
            }
            set {
                this["IsAutoSave"] = value;
            }
        }
    }
}
